services:
  mysql:
    image: mysql:8.0
    container_name: jelou-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jelou_db
      MYSQL_USER: jelou
      MYSQL_PASSWORD: jelou
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./db/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./db/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql

volumes:
  data:  